/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ttotConcertProxySol from "./TTOT_Concert_Proxy.sol";
export type { ttotConcertProxySol };
export type { Concert_V1 } from "./Concert_V1";
export type { Factory_V1 } from "./Factory_V1";
