/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as encodeCallSol from "./EncodeCall.sol";
export type { encodeCallSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as jumpball from "./jumpball";
export type { jumpball };
import type * as ttot from "./ttot";
export type { ttot };
export type { EventTest } from "./EventTest";
export type { Exchange } from "./Exchange";
export type { Factory } from "./Factory";
export type { GrayToken } from "./GrayToken";
export type { MasterChef } from "./MasterChef";
export type { StakingRewards } from "./StakingRewards";
export type { Token } from "./Token";
