import Head from 'next/head';
import React from 'react';
import styled from 'styled-components';

interface Props {
  children: React.ReactNode;
}
const HomeLayout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>seed-vault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>{children}</Layout>;
    </>
  );
};

const Layout = styled('section')`
  max-width: 1024px;
  margin: auto;
  height: 100vh;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

export default HomeLayout;
